name: django-stack-template

description: This stack will help you create an awesome Django stack

branding:
  icon: bell # https://feathericons.com/
  color: red # hex accepted

#-------------------------------------------------------------
# All values needed to be provided/verified by the user should be defined as inputs.
# Values can be provided using a values file (yaml/json/.env format) or from the UX.
# Default values are defined by stack authors using **default: <Value>**
# All inputs defined here are optional unless they are marked **required: true**
# All inputs will be of String type by default unless specified as **type:boolean**
# All inputs will be considered as non-secrets unless specified as **is_secret:true**
# All inputs will be available for scripts/workflows run as part of stack init
# Any input that is not explicitly configured as Repo/Environment secret will NOT be available in the new stack

inputs:
  - name: AZURE_APP_NAME
    description: Enter the name of the Azure App which has been configured to host the website
    is-secret: true
    required: true
    
  - name: AZURE_WEBAPP_PUBLISH_PROFILE
    description: Enter the Azure Publish profile. 
    is-secret: true
    required: true

#-------------------------------------------------------------

configs:
  # Meta data for creating the new repository
  repo-metadata:
      parameters:
        description: 'A Django website deployed in Azure App Service'
        secrets: 
          - name: AZURE_APP_NAME
            value: ${{inputs.AZURE_APP_NAME}}
          - name: AZURE_WEBAPP_PUBLISH_PROFILE
            value: ${{inputs.AZURE_WEBAPP_PUBLISH_PROFILE}}
        topics:
        - django
        - python
        - azure
      
  # Branch Protection rules
  # branches:
  #   - name: release_v? #branch name or pattern you want to protect
  #     parameters:
  #       enforce-admins: true / false
  #       required-pull-request-reviews:
  #         dismiss-stale-reviews: true / false
  #         require-code-owner-reviews: true / false
  #         required-approving-review-count: 1 # integer
  #       allow-force-pushes: true / false
  #       allow-deletions: true / false

  # Security and configuration settings to be enabled/disabled
  # security:
  #   parameters: 
  #     vulnerability-alerts: true / false
  #     automated-security-fixes: true # can be true only if vulnerability-alerts is true


#-------------------------------------------------------------
# GitHub Apps to be installed
# just provide the slugs
# github-apps:
# - slug: sample1
# - slug: sample2


#-------------------------------------------------------------
# Initialization workflow to run
# This workflow file will NOT be part of the stack (new repo created). 
# workflow could use the stack inputs using the notation : ${{ github.event.inputs.name }}
init:
  uses: "stack-init.yml" # you would have to create a workflow - .github/workflows/stack-init.yml
