name: django-azure-template

description: This stack will help you create an awesome Django stack and deploy to Azure

branding:
  icon: bell # https://feathericons.com/
  color: red # hex accepted

inputs:
  - name: AZURE_APP_NAME
    description: Enter the name of the Azure App which has been configured to host the website
    is-secret: false
    required: true
    
  - name: AZURE_WEBAPP_PUBLISH_PROFILE
    description: Enter the Azure Publish profile. 
    is-secret: true
    required: true

configs:
  repo-metadata:
      parameters:
        description: 'A Django website deployed in Azure App Service'
        secrets: 
          - name: AZURE_WEBAPP_PUBLISH_PROFILE
            value: ${{inputs.AZURE_WEBAPP_PUBLISH_PROFILE}}
        topics:
        - django
        - python
        - azure
        
  environments:
    - name: development
      parameters:
        protected-branches: false
        allowed-branch-rules:
          - main
          - releases/*
      
init:
  uses: "stack-init.yml" # you would have to create a workflow - .github/workflows/stack-init.yml
